# -*- encoding: utf-8 -*-
$:.push File.expand_path('../lib', __FILE__)
require 'calabash-cucumber/version'

# ruby files
ruby_files = Dir.glob('lib/**/*.rb') + Dir.glob('bin/**/*.rb')

# additional files in bin
additional_bin_files = %w(bin/cal.xcconfig bin/CalabashSetup bin/calabash-ios)

# bin help file
bin_help = %w(doc/calabash-ios-help.txt)

# files in script
scripts = %w(scripts/.irbrc)

# files in script/data
scripts_data = Dir.glob('scripts/data/*.plist')

# pre-defined Steps
features = Dir.glob('features/**/*.rb')

# resources for the skeleton project generated by calabash-ios gen
features_skeleton = Dir.glob('features-skeleton/**/*.*')

license = %w(LICENSE)

gem_files = ruby_files + additional_bin_files + bin_help + scripts + scripts_data + features + features_skeleton + license

Gem::Specification.new do |s|
  s.name        = 'calabash-cucumber'
  s.version     = Calabash::Cucumber::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['Karl Krukow']
  s.email       = ['karl@lesspainful.com']
  s.homepage    = 'http://calaba.sh'
  s.summary     = %q{Client for calabash-ios-server for automated functional testing on iOS}
  s.description = %q{calabash-cucumber drives tests for native iOS apps. You must link your app with calabash-ios-server framework to execute tests.}
  s.files         = gem_files
  s.test_files    = []
  s.executables   = %w(calabash-ios)
  s.require_paths = %w(lib)
  s.license       = 'EPL-1.0'

  s.required_ruby_version = '>= 2.0'

  s.add_dependency 'clipboard'
  s.add_dependency 'cucumber'
  s.add_dependency 'geocoder'
  s.add_dependency 'httpclient'
  s.add_dependency 'run_loop', '>= 4.2', '< 5.0'
  # FIXME: dependency of 'run_loop'
  s.add_dependency 'mutex_m'
  s.add_dependency 'slowhandcuke'

  # Shared with run-loop.
  s.add_dependency 'awesome_print'
  s.add_dependency 'json'
end
